export const GET_CONTENT_DATA = "GET_CONTENT_DATA";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const ADD_HISTORY_SEARCH = "ADD_HISTORY_SEARCH";
